# ------------------------------
# Usage: copy content generated by this script to ${QuartusProject}/${ProjectName}.qsf
# Reference: https://www.terasic.com.tw/wiki/images/f/f2/DE2_115_manual.pdf
# ------------------------------

import re

pin_bind = ""

# clock
pin_bind += "set_location_assignment PIN_Y2 -to clk\n"

# reset (KEY0)
pin_bind += "set_location_assignment PIN_M23 -to rst\n"

# segment-7 bins
segment_7  = """
HEX0[0] PIN_G18 Seven Segment Digit 0[0] 2.5V
HEX0[1] PIN_F22 Seven Segment Digit 0[1] 2.5V
HEX0[2] PIN_E17 Seven Segment Digit 0[2] 2.5V
HEX0[3] PIN_L26 Seven Segment Digit 0[3] Depending on JP7
HEX0[4] PIN_L25 Seven Segment Digit 0[4] Depending on JP7
HEX0[5] PIN_J22 Seven Segment Digit 0[5] Depending on JP7
HEX0[6] PIN_H22 Seven Segment Digit 0[6] Depending on JP7
HEX1[0] PIN_M24 Seven Segment Digit 1[0] Depending on JP7
HEX1[1] PIN_Y22 Seven Segment Digit 1[1] Depending on JP7
HEX1[2] PIN_W21 Seven Segment Digit 1[2] Depending on JP7
HEX1[3] PIN_W22 Seven Segment Digit 1[3] Depending on JP7
HEX1[4] PIN_W25 Seven Segment Digit 1[4] Depending on JP7
HEX1[5] PIN_U23 Seven Segment Digit 1[5] Depending on JP7
HEX1[6] PIN_U24 Seven Segment Digit 1[6] Depending on JP7
HEX2[0] PIN_AA25 Seven Segment Digit 2[0] Depending on JP7
HEX2[1] PIN_AA26 Seven Segment Digit 2[1] Depending on JP7
HEX2[2] PIN_Y25 Seven Segment Digit 2[2] Depending on JP7
HEX2[3] PIN_W26 Seven Segment Digit 2[3] Depending on JP7
HEX2[4] PIN_Y26 Seven Segment Digit 2[4] Depending on JP7
HEX2[5] PIN_W27 Seven Segment Digit 2[5] Depending on JP7
HEX2[6] PIN_W28 Seven Segment Digit 2[6] Depending on JP7
HEX3[0] PIN_V21 Seven Segment Digit 3[0] Depending on JP7
HEX3[1] PIN_U21 Seven Segment Digit 3[1] Depending on JP7
HEX3[2] PIN_AB20 Seven Segment Digit 3[2] Depending on JP6
HEX3[3] PIN_AA21 Seven Segment Digit 3[3] Depending on JP6
HEX3[4] PIN_AD24 Seven Segment Digit 3[4] Depending on JP6
HEX3[5] PIN_AF23 Seven Segment Digit 3[5] Depending on JP6
HEX3[6] PIN_Y19 Seven Segment Digit 3[6] Depending on JP6
HEX4[0] PIN_AB19 Seven Segment Digit 4[0] Depending on JP6
HEX4[1] PIN_AA19 Seven Segment Digit 4[1] Depending on JP6
HEX4[2] PIN_AG21 Seven Segment Digit 4[2] Depending on JP6
HEX4[3] PIN_AH21 Seven Segment Digit 4[3] Depending on JP6
HEX4[4] PIN_AE19 Seven Segment Digit 4[4] Depending on JP6
HEX4[5] PIN_AF19 Seven Segment Digit 4[5] Depending on JP6
HEX4[6] PIN_AE18 Seven Segment Digit 4[6] Depending on JP6
HEX5[0] PIN_AD18 Seven Segment Digit 5[0] Depending on JP6
HEX5[1] PIN_AC18 Seven Segment Digit 5[1] Depending on JP6
HEX5[2] PIN_AB18 Seven Segment Digit 5[2] Depending on JP6
HEX5[3] PIN_AH19 Seven Segment Digit 5[3] Depending on JP6
HEX5[4] PIN_AG19 Seven Segment Digit 5[4] Depending on JP6
HEX5[5] PIN_AF18 Seven Segment Digit 5[5] Depending on JP6
HEX5[6] PIN_AH18 Seven Segment Digit 5[6] Depending on JP6
HEX6[0] PIN_AA17 Seven Segment Digit 6[0] Depending on JP6
HEX6[1] PIN_AB16 Seven Segment Digit 6[1] Depending on JP6
HEX6[2] PIN_AA16 Seven Segment Digit 6[2] Depending on JP6
HEX6[3] PIN_AB17 Seven Segment Digit 6[3] Depending on JP6
HEX6[4] PIN_AB15 Seven Segment Digit 6[4] Depending on JP6
HEX6[5] PIN_AA15 Seven Segment Digit 6[5] Depending on JP6
HEX6[6] PIN_AC17 Seven Segment Digit 6[6] Depending on JP6
HEX7[0] PIN_AD17 Seven Segment Digit 7[0] Depending on JP6
HEX7[1] PIN_AE17 Seven Segment Digit 7[1] Depending on JP6
HEX7[2] PIN_AG17 Seven Segment Digit 7[2] Depending on JP6
HEX7[3] PIN_AH17 Seven Segment Digit 7[3] Depending on JP6
HEX7[4] PIN_AF17 Seven Segment Digit 7[4] Depending on JP6
HEX7[5] PIN_AG18 Seven Segment Digit 7[5] Depending on JP6
HEX7[6] PIN_AA14 Seven Segment Digit 7[6] 3.3V
"""

pattern = re.compile(r'HEX(\d+)\[(\d+)\]\s+PIN_([A-Z0-9]+)')

for line in segment_7.splitlines():
    match = pattern.search(line)
    if match:
        hex_idx, bit_idx, pin = match.groups()
        pin_bind += f"set_location_assignment PIN_{pin} -to seg{hex_idx}[{bit_idx}]\n"

with open("./port2pin.txt", "w") as f:
	f.write(pin_bind)